### ISSUE TITLE
Running "dotdocker start" failed on Git Bash in Windows 10 Pro

### ISSUE THREAD

**Issue by yanalanhe** [aj-may/dotdocker#35]
**Describe the bug** A clear and concise description of what the bug is.
On Git Bash on Windows 10 Pro Running "dotdocker start" failed 

**To Reproduce** Steps to reproduce the behavior:
1. Open Git Bash on Windows 10
2. Clone dotdocker and running "npm install -g dotdocker" succeeded.
3. Run "dotdocker start"

**Expected behavior** A clear and concise description of what you expected to happen.
dotdocker is expected to start

**Actual behaviors**
Running "dotdocker start" failed with following error:
**Screenshots** If applicable, add screenshots to help explain your problem.
https://user-images.githubusercontent.com/43561509/80061699-0181cf00-8500-11ea-91c9-f039efe48153.png

**Additional context** Add any other context about the problem here.
Platform: Windows 10 Pro - 10.0.18363 Build 18363
Subsystem: Git Bash

**Comment by aj-may** [comment]
Sorry, but because limitations of setting up a custom DNS server on windows, we are unable to support windows in a meaningful way.
