### ISSUE TITLE
Dotdocker start issue in windows 10

### ISSUE THREAD

**Issue by ParvathyPB25** [aj-may/dotdocker#36]
Tried to start dotdocker in windows 10 machine but getting following error:
command used **dotdocker start**
  **> Start dotdocker containers
    > Start proxy
      × Pulling codekitchen/dinghy-http-proxy:latest
        → connect ENOENT //./pipe/docker_engine
        Creating dotdocker-proxy
        Starting dotdocker-proxy
    > Start dnsmasq
      \ Pulling andyshinn/dnsmasq:latest
        Creating dotdocker-dnsmasq
        Starting dotdocker-dnsmasq
    Setting up DNS
(node:27208) UnhandledPromiseRejectionWarning: Error: connect ENOENT //./pipe/docker_engine
    at PipeConnectWrap.afterConnect [as oncomplete] (net.js:1142:16)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:27208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:27208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.**

**Comment by aj-may** [comment]
Sorry, but because limitations of setting up a custom DNS server on windows, we are unable to support windows in a meaningful way.
